console.log("js in javascript code");
const x = document.getElementById('heading');
console.log(x);
const y = document.getElementsByClassName('heading');
console.log(y);
console.log(y[1]);
console.log(y[0]);
const z = document.getElementsByTagName('h2');
console.log(z);
console.log(z[0]);
console.log(z[1]);
console.log(z[2]);
const a = document.querySelector('#heading');
console.log(a);
const b = document.querySelector('.heading');
console.log(b);
const c = document.querySelectorAll('.heading');
console.log(c);
console.log(c[0]);
console.log(c[1]);
