let a=null;
let b=1;
let c=true;
let d=BigInt("567")+BigInt("3");
let e="Harry";
let f=Symbol("I'm a nice symbol");
let g=undefined;
console.log(a, b, c, d, e, f, g);
console.log(typeof a);
console.log(typeof b);
console.log(typeof c);
console.log(typeof d);
console.log(typeof e);
console.log(typeof f);
console.log(typeof g);